package vn.travel.domain.model

class AttractionModel(
    val id: Int,
    val name: String,
    val nameZh: String,
    val openStatus: Int,
    val introduction: String,
    val openTime: String,
    val zipcode: String,
    val distric: String,
    val address: String,
    val tel: String,
    val fax: String,
    val email: String,
    val months: String,
    val nLat: Double,
    val eLong: Double,
    val officialSite: String,
    val facebook: String,
    val ticket: String,
    val remind: String,
    val modified: String,
    val url: String,
    val category: List<CategoryModel> = listOf(),
    val target: List<TargetModel> = listOf(),
    val service: List<ServiceModel> = listOf(),
    val friendly: List<String> = listOf(),
    val images: List<ImageModel> = listOf(),
    val files: List<String> = listOf(),
    val links: List<String> = listOf()
) : BaseModel()